In [4]:
# 1creating nd array
import numpy as np
arr1=np.array([1,2,3,4])


In [5]:
arr1

array([1, 2, 3, 4])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr2=np.array([[1,23,4],[6,8,9]])

In [8]:
arr2

array([[ 1, 23,  4],
       [ 6,  8,  9]])

In [9]:
# 2
arr3=np.zeros((2,3))

In [10]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4=np.ones((3,3))

In [12]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr5=np.identity(5)

In [14]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr7=np.arange(5,16,2)

In [17]:
arr7

array([ 5,  7,  9, 11, 13, 15])

In [18]:

arr8=np.linspace(10,20,10)

In [19]:
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [20]:
arr9=arr8.copy()

In [21]:
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [22]:
arr2.shape

(2, 3)

In [23]:
arr2

array([[ 1, 23,  4],
       [ 6,  8,  9]])

In [24]:
arr2.ndim

2

In [25]:
arr5.ndim

2

In [26]:
arr5.size

25

In [27]:
arr9.dtype

dtype('float64')

In [28]:
arr5.astype('int') 
# data cleaning

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
# numpy array vs python list
lista=range(100)
arr11=np.arange(100)


In [30]:
import sys

In [31]:
print(sys.getsizeof(87)*len(lista))

2800


In [32]:
print(arr11.itemsize*arr11.size)

400


In [33]:
import time

In [34]:
x=range(10000000)
y=range(10000000,20000000)
start_time=time.time()
# c=[(x,y) for x,y in zip(x,y)]
c=[(x+y) for x,y in zip(x,y)]
print(time.time()-start_time)

2.939159870147705


In [37]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start_time=time.time()
c=a+b
print(time.time()-start_time)



0.16316771507263184


In [44]:
arr12=np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [45]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
arr12[2]

array([ 8,  9, 10, 11])

In [50]:
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
arr12[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [53]:
arr12[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [57]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [63]:
arr12[4:6,2:4]

array([[18, 19],
       [22, 23]])

In [64]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [66]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [67]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [68]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [69]:
arr1/arr2

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
       0.66666667])

In [70]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [71]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [82]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)
print(arr3)
arr4

[[0 1 2]
 [3 4 5]]


array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [78]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [83]:
arr1.dot(arr2)

154

In [84]:
arr4.max()

11

In [86]:
arr3.min(axis=0)

array([0, 1, 2])

In [87]:
arr3.min(axis=1)

array([0, 3])

In [88]:
arr4.min(axis=0)

array([6, 7])

In [89]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [92]:
arr4.max(axis=0)

array([10, 11])

In [93]:
arr4.max(axis=1)

array([ 7,  9, 11])

In [94]:
arr4.sum(axis=0)

array([24, 27])

In [95]:
arr4.sum(axis=1)

array([13, 17, 21])

In [96]:
arr4.mean()

8.5

In [98]:
arr4.std()

1.707825127659933

In [99]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [100]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

# reshaping numpy

In [101]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [102]:
arr4.ndim

2

In [103]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [104]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [105]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [106]:
arr5=np.arange(12,18).reshape(2,3)

In [107]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

In [109]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [111]:
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [116]:
np.hsplit(arr5,3)

[array([[12],
        [15]]),
 array([[13],
        [16]]),
 array([[14],
        [17]])]

In [117]:
np.vsplit(arr5,2)

[array([[12, 13, 14]]), array([[15, 16, 17]])]

In [118]:
arr8=np.arange(24).reshape(6,4)

In [119]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [120]:
arr8[[1,3,5]]    #fancy indexing

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [125]:
arr8[:,[0,1,3]]

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11],
       [12, 13, 15],
       [16, 17, 19],
       [20, 21, 23]])

# indexing using boolean array

In [126]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[67, 50, 36, 84, 40],
       [84, 81, 87, 68, 57],
       [14, 52, 55, 90,  7],
       [34, 75, 69, 62, 53]])

In [127]:
arr[0][2]

36

In [128]:
arr>50

array([[ True, False, False,  True, False],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True,  True]])

In [129]:
#indexing using boolean array/filtering
arr[arr>50]

array([67, 84, 84, 81, 87, 68, 57, 52, 55, 90, 75, 69, 62, 53])

In [130]:
arr[(arr>50) & (arr%2!=0)]

array([67, 81, 87, 57, 55, 75, 69, 53])